BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DO $$ BEGIN CREATE TYPE user_role AS ENUM ('admin','analyst','viewer'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE source_access AS ENUM ('public','authorized','restricted_metadata_only'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE source_ingestion AS ENUM ('manual','upload','web_fetch','api','import'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE company_status AS ENUM ('active','inactive','acquired','defunct','unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE record_status AS ENUM ('draft','active','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE ownership_type AS ENUM ('private','public','subsidiary','government','joint_venture','cooperative','unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE identifier_type AS ENUM ('cage','duns','uei','lei','naics','sic','ticker','internal'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE contact_verification_status AS ENUM ('unverified','source_verified','directly_verified','stale','invalid'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE qualification_scarcity AS ENUM ('confirmed_sole_source','confirmed_constrained_source','likely_dominant_source','unverified_company_claim','multiple_qualified_sources','not_assessed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE observation_review_status AS ENUM ('pending','accepted','rejected','superseded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE observation_conflict_status AS ENUM ('none','potential','confirmed','resolved'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE research_target_type AS ENUM ('company','facility','contact','platform','part','qualification','data_source'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE research_run_status AS ENUM ('queued','running','succeeded','failed','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE proposal_status AS ENUM ('pending','accepted','rejected','superseded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE import_status AS ENUM ('queued','validating','ready','processing','completed','failed','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE evidence_extraction_status AS ENUM ('pending','processing','completed','failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE financial_metric AS ENUM ('revenue','ebitda','operating_income','net_income','backlog','enterprise_value'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE observation_value_kind AS ENUM ('text','number','boolean','date','money','range','entity_reference','structured'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE research_tool_call_status AS ENUM ('started','succeeded','failed','blocked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE model_usage_status AS ENUM ('succeeded','failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE proposal_review_decision AS ENUM ('accepted','rejected','superseded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE merge_status AS ENUM ('applied','reverted'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE import_row_status AS ENUM ('pending','validated','imported','rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL, display_name text NOT NULL, password_hash text NOT NULL, role user_role NOT NULL DEFAULT 'viewer', is_disabled boolean NOT NULL DEFAULT false, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx ON users(lower(email));
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash varchar(64) NOT NULL UNIQUE, csrf_token_hash varchar(64) NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, last_seen_at timestamptz, ip_hash varchar(64), user_agent text, created_at timestamptz NOT NULL DEFAULT now(), CHECK (expires_at > created_at));
CREATE INDEX IF NOT EXISTS sessions_user_expiry_idx ON sessions(user_id,expires_at);
CREATE TABLE IF NOT EXISTS rate_limits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL, subject_hash varchar(64) NOT NULL, window_started_at timestamptz NOT NULL, window_seconds integer NOT NULL CHECK(window_seconds>0), request_count integer NOT NULL DEFAULT 0 CHECK(request_count>=0), expires_at timestamptz NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(scope,subject_hash,window_started_at));
CREATE INDEX IF NOT EXISTS rate_limits_expires_idx ON rate_limits(expires_at);

CREATE TABLE IF NOT EXISTS companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), legal_name text NOT NULL, display_name text NOT NULL, description text, status company_status NOT NULL DEFAULT 'active', headquarters_country_code varchar(2), website_url text, founded_year integer CHECK(founded_year IS NULL OR founded_year BETWEEN 1700 AND 2200), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS companies_name_trgm_idx ON companies USING gin(display_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS companies_search_idx ON companies USING gin(to_tsvector('english',coalesce(legal_name,'')||' '||coalesce(display_name,'')||' '||coalesce(description,'')));
CREATE TABLE IF NOT EXISTS company_aliases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE, alias text NOT NULL, alias_type text NOT NULL DEFAULT 'name', is_primary boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS company_aliases_company_alias_uidx ON company_aliases(company_id,lower(alias)); CREATE INDEX IF NOT EXISTS company_aliases_trgm_idx ON company_aliases USING gin(alias gin_trgm_ops);
CREATE TABLE IF NOT EXISTS company_domains (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE, domain text NOT NULL, is_primary boolean NOT NULL DEFAULT false, verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX IF NOT EXISTS company_domains_domain_uidx ON company_domains(lower(domain));
CREATE TABLE IF NOT EXISTS company_identifiers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE, type identifier_type NOT NULL, value text NOT NULL, issuing_country_code varchar(2), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX IF NOT EXISTS company_identifiers_natural_uidx ON company_identifiers(type,upper(value),coalesce(issuing_country_code,''));
CREATE TABLE IF NOT EXISTS facilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE SET NULL, name text NOT NULL, facility_type text, address_line_1 text, address_line_2 text, city text, region text, postal_code text, country_code varchar(2) NOT NULL, latitude numeric(9,6), longitude numeric(9,6), status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((latitude IS NULL OR latitude BETWEEN -90 AND 90) AND (longitude IS NULL OR longitude BETWEEN -180 AND 180)));
CREATE INDEX IF NOT EXISTS facilities_company_idx ON facilities(company_id); CREATE INDEX IF NOT EXISTS facilities_name_trgm_idx ON facilities USING gin(name gin_trgm_ops);
CREATE TABLE IF NOT EXISTS contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE SET NULL, facility_id uuid REFERENCES facilities(id) ON DELETE SET NULL, full_name text NOT NULL, title text, email text, phone text, verification_status contact_verification_status NOT NULL DEFAULT 'unverified', verified_at timestamptz, status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(company_id IS NOT NULL OR facility_id IS NOT NULL)); CREATE INDEX IF NOT EXISTS contacts_name_trgm_idx ON contacts USING gin(full_name gin_trgm_ops);

CREATE TABLE IF NOT EXISTS capabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), parent_id uuid REFERENCES capabilities(id) ON DELETE RESTRICT, code text NOT NULL UNIQUE, name text NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS capabilities_search_idx ON capabilities USING gin(to_tsvector('english',name||' '||coalesce(description,'')));
CREATE TABLE IF NOT EXISTS company_capabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE, capability_id uuid NOT NULL REFERENCES capabilities(id) ON DELETE RESTRICT, status record_status NOT NULL DEFAULT 'active', confidence numeric(5,4), valid_from date, valid_to date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,capability_id), CHECK((confidence IS NULL OR confidence BETWEEN 0 AND 1) AND (valid_from IS NULL OR valid_to IS NULL OR valid_from<=valid_to)));
CREATE TABLE IF NOT EXISTS facility_capabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), facility_id uuid NOT NULL REFERENCES facilities(id) ON DELETE CASCADE, capability_id uuid NOT NULL REFERENCES capabilities(id) ON DELETE RESTRICT, status record_status NOT NULL DEFAULT 'active', confidence numeric(5,4), valid_from date, valid_to date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(facility_id,capability_id), CHECK((confidence IS NULL OR confidence BETWEEN 0 AND 1) AND (valid_from IS NULL OR valid_to IS NULL OR valid_from<=valid_to)));
CREATE TABLE IF NOT EXISTS certifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, facility_id uuid REFERENCES facilities(id) ON DELETE CASCADE, standard text NOT NULL, certificate_number text, issuing_body text, issued_on date, expires_on date, status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(num_nonnulls(company_id,facility_id)=1 AND (issued_on IS NULL OR expires_on IS NULL OR issued_on<=expires_on)));

CREATE TABLE IF NOT EXISTS platform_families (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, manufacturer_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS platforms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), family_id uuid REFERENCES platform_families(id) ON DELETE SET NULL, name text NOT NULL, platform_type text, manufacturer_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS platforms_name_trgm_idx ON platforms USING gin(name gin_trgm_ops);
CREATE TABLE IF NOT EXISTS platform_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), platform_id uuid NOT NULL REFERENCES platforms(id) ON DELETE CASCADE, name text NOT NULL, designation text, entered_service_on date, retired_on date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(platform_id,name), CHECK(entered_service_on IS NULL OR retired_on IS NULL OR entered_service_on<=retired_on));
CREATE TABLE IF NOT EXISTS subsystems (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), parent_id uuid REFERENCES subsystems(id) ON DELETE RESTRICT, code text UNIQUE, name text NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS parts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), manufacturer_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, part_number text NOT NULL, name text, description text, lifecycle_status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS parts_number_trgm_idx ON parts USING gin(part_number gin_trgm_ops); CREATE INDEX IF NOT EXISTS parts_search_idx ON parts USING gin(to_tsvector('english',part_number||' '||coalesce(name,'')||' '||coalesce(description,'')));
CREATE TABLE IF NOT EXISTS part_alternate_ids (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), part_id uuid NOT NULL REFERENCES parts(id) ON DELETE CASCADE, identifier_type text NOT NULL, identifier_value text NOT NULL, authority text, created_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX IF NOT EXISTS part_alternate_ids_natural_uidx ON part_alternate_ids(identifier_type,upper(identifier_value),coalesce(authority,''));
CREATE TABLE IF NOT EXISTS facility_qualifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), facility_id uuid NOT NULL REFERENCES facilities(id) ON DELETE CASCADE, part_id uuid NOT NULL REFERENCES parts(id) ON DELETE CASCADE, platform_id uuid REFERENCES platforms(id) ON DELETE CASCADE, platform_variant_id uuid REFERENCES platform_variants(id) ON DELETE CASCADE, subsystem_id uuid REFERENCES subsystems(id) ON DELETE SET NULL, customer_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, qualification_reference text, scarcity qualification_scarcity NOT NULL DEFAULT 'not_assessed', valid_from date, valid_to date, confidence numeric(5,4), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((platform_variant_id IS NULL OR platform_id IS NOT NULL) AND (valid_from IS NULL OR valid_to IS NULL OR valid_from<=valid_to) AND (confidence IS NULL OR confidence BETWEEN 0 AND 1)));
CREATE UNIQUE INDEX IF NOT EXISTS facility_qualifications_context_uidx ON facility_qualifications(facility_id,part_id,platform_id,platform_variant_id,subsystem_id,customer_company_id,valid_from) NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_number text NOT NULL, title text, awarding_organization text, customer_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, supplier_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, platform_id uuid REFERENCES platforms(id) ON DELETE SET NULL, start_date date, end_date date, amount_lower numeric(22,2), amount_upper numeric(22,2), currency varchar(3), status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((amount_lower IS NULL OR amount_upper IS NULL OR amount_lower<=amount_upper) AND (start_date IS NULL OR end_date IS NULL OR start_date<=end_date)));
CREATE INDEX IF NOT EXISTS contracts_search_idx ON contracts USING gin(to_tsvector('english',contract_number||' '||coalesce(title,'')||' '||coalesce(awarding_organization,'')));
CREATE TABLE IF NOT EXISTS procurements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_id uuid REFERENCES contracts(id) ON DELETE SET NULL, buyer_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, supplier_company_id uuid REFERENCES companies(id) ON DELETE SET NULL, facility_id uuid REFERENCES facilities(id) ON DELETE SET NULL, part_id uuid REFERENCES parts(id) ON DELETE SET NULL, solicitation_number text, award_number text, quantity_lower numeric(20,4), quantity_upper numeric(20,4), unit text, amount_lower numeric(22,2), amount_upper numeric(22,2), currency varchar(3), awarded_on date, delivery_from date, delivery_to date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((quantity_lower IS NULL OR quantity_upper IS NULL OR quantity_lower<=quantity_upper) AND (amount_lower IS NULL OR amount_upper IS NULL OR amount_lower<=amount_upper) AND (delivery_from IS NULL OR delivery_to IS NULL OR delivery_from<=delivery_to)));

CREATE TABLE IF NOT EXISTS data_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, source_type text NOT NULL, base_url text, access source_access NOT NULL DEFAULT 'public', ingestion source_ingestion NOT NULL DEFAULT 'manual', publisher text, jurisdiction text, reliability_score numeric(5,2), freshness_score numeric(5,2), authority_score numeric(5,2), notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((reliability_score IS NULL OR reliability_score BETWEEN 0 AND 100) AND (freshness_score IS NULL OR freshness_score BETWEEN 0 AND 100) AND (authority_score IS NULL OR authority_score BETWEEN 0 AND 100)));
CREATE TABLE IF NOT EXISTS source_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), data_source_id uuid NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT, canonical_url text, title text, document_type text, published_on date, retrieved_at timestamptz NOT NULL DEFAULT now(), content_sha256 varchar(64), storage_key text, mime_type text, byte_length bigint, language_code varchar(16), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), CHECK((canonical_url IS NOT NULL OR storage_key IS NOT NULL) AND (byte_length IS NULL OR byte_length>=0)));
CREATE UNIQUE INDEX IF NOT EXISTS source_documents_hash_uidx ON source_documents(content_sha256); CREATE INDEX IF NOT EXISTS source_documents_title_trgm_idx ON source_documents USING gin(title gin_trgm_ops);
CREATE TABLE IF NOT EXISTS company_source_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), data_source_id uuid NOT NULL REFERENCES data_sources(id) ON DELETE CASCADE, company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE, relationship text NOT NULL DEFAULT 'mentions', external_key text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(data_source_id,company_id,relationship));
CREATE TABLE IF NOT EXISTS source_document_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_document_id uuid NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE, company_id uuid REFERENCES companies(id) ON DELETE CASCADE, facility_id uuid REFERENCES facilities(id) ON DELETE CASCADE, part_id uuid REFERENCES parts(id) ON DELETE CASCADE, platform_id uuid REFERENCES platforms(id) ON DELETE CASCADE, contract_id uuid REFERENCES contracts(id) ON DELETE CASCADE, relationship text NOT NULL DEFAULT 'mentions', created_at timestamptz NOT NULL DEFAULT now(), CHECK(num_nonnulls(company_id,facility_id,part_id,platform_id,contract_id)=1));
CREATE TABLE IF NOT EXISTS evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_document_id uuid NOT NULL REFERENCES source_documents(id) ON DELETE RESTRICT, extraction_status evidence_extraction_status NOT NULL DEFAULT 'pending', quote text, locator text, page_number integer, start_offset integer, end_offset integer, extracted_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, extraction_method text NOT NULL, content_sha256 varchar(64), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), CHECK((quote IS NOT NULL OR locator IS NOT NULL) AND (page_number IS NULL OR page_number>0) AND (start_offset IS NULL OR end_offset IS NULL OR (start_offset>=0 AND start_offset<=end_offset))));

CREATE TABLE IF NOT EXISTS ownership_observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, parent_company_id uuid REFERENCES companies(id) ON DELETE RESTRICT, type ownership_type NOT NULL, owner_name text, ownership_percent_lower numeric(7,4), ownership_percent_upper numeric(7,4), valid_from date, valid_to date, confidence numeric(5,4) NOT NULL CHECK(confidence BETWEEN 0 AND 1), evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE RESTRICT, observed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), CHECK((parent_company_id IS NOT NULL OR owner_name IS NOT NULL) AND (ownership_percent_lower IS NULL OR ownership_percent_upper IS NULL OR ownership_percent_lower<=ownership_percent_upper) AND (valid_from IS NULL OR valid_to IS NULL OR valid_from<=valid_to)));
CREATE TABLE IF NOT EXISTS financial_observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, metric financial_metric NOT NULL, amount_lower numeric(22,2), amount_upper numeric(22,2), currency varchar(3) NOT NULL, period_start date, period_end date, fiscal_year integer, confidence numeric(5,4) NOT NULL CHECK(confidence BETWEEN 0 AND 1), evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE RESTRICT, observed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), CHECK((amount_lower IS NULL OR amount_upper IS NULL OR amount_lower<=amount_upper) AND (period_start IS NULL OR period_end IS NULL OR period_start<=period_end)));
CREATE TABLE IF NOT EXISTS employee_observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, employee_count_lower integer, employee_count_upper integer, as_of_date date, confidence numeric(5,4) NOT NULL CHECK(confidence BETWEEN 0 AND 1), evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE RESTRICT, observed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), CHECK((employee_count_lower IS NULL OR employee_count_lower>=0) AND (employee_count_upper IS NULL OR employee_count_upper>=0) AND (employee_count_lower IS NULL OR employee_count_upper IS NULL OR employee_count_lower<=employee_count_upper)));
CREATE TABLE IF NOT EXISTS observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL, subject_id uuid NOT NULL, field_key text NOT NULL, value_kind observation_value_kind NOT NULL, value jsonb NOT NULL, normalized_text text, unit text, valid_from date, valid_to date, observed_at timestamptz NOT NULL DEFAULT now(), confidence numeric(5,4) NOT NULL CHECK(confidence BETWEEN 0 AND 1), evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE RESTRICT, review_status observation_review_status NOT NULL DEFAULT 'pending', conflict_status observation_conflict_status NOT NULL DEFAULT 'none', created_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(valid_from IS NULL OR valid_to IS NULL OR valid_from<=valid_to));
CREATE INDEX IF NOT EXISTS observations_subject_field_idx ON observations(subject_type,subject_id,field_key,observed_at);

CREATE TABLE IF NOT EXISTS research_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_type research_target_type NOT NULL, target_id uuid, requested_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, status research_run_status NOT NULL DEFAULT 'queued', objective text NOT NULL, input jsonb NOT NULL DEFAULT '{}', prompt_version text NOT NULL, progress_percent numeric(5,2), error_code text, error_message text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((progress_percent IS NULL OR progress_percent BETWEEN 0 AND 100) AND (started_at IS NULL OR completed_at IS NULL OR started_at<=completed_at)));
CREATE TABLE IF NOT EXISTS research_tool_calls (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), research_run_id uuid NOT NULL REFERENCES research_runs(id) ON DELETE RESTRICT, sequence integer NOT NULL CHECK(sequence>=0), tool_name text NOT NULL, status research_tool_call_status NOT NULL, request jsonb NOT NULL, response jsonb, request_sha256 varchar(64) NOT NULL, response_sha256 varchar(64), started_at timestamptz NOT NULL, completed_at timestamptz, duration_ms integer, error jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(research_run_id,sequence));
CREATE TABLE IF NOT EXISTS model_usage (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), research_run_id uuid NOT NULL REFERENCES research_runs(id) ON DELETE RESTRICT, sequence integer NOT NULL CHECK(sequence>=0), provider text NOT NULL, model text NOT NULL, status model_usage_status NOT NULL, prompt_sha256 varchar(64) NOT NULL, response_sha256 varchar(64), request jsonb NOT NULL, response jsonb, input_tokens integer, output_tokens integer, cost_usd numeric(14,8), latency_ms integer, error jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(research_run_id,sequence), CHECK((input_tokens IS NULL OR input_tokens>=0) AND (output_tokens IS NULL OR output_tokens>=0) AND (cost_usd IS NULL OR cost_usd>=0)));
CREATE TABLE IF NOT EXISTS research_proposals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), research_run_id uuid NOT NULL REFERENCES research_runs(id) ON DELETE RESTRICT, observation_id uuid NOT NULL REFERENCES observations(id) ON DELETE RESTRICT, subject_type text NOT NULL, subject_id uuid NOT NULL, field_key text NOT NULL, status proposal_status NOT NULL DEFAULT 'pending', rationale text, proposed_by_model_usage_id uuid REFERENCES model_usage(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(research_run_id,observation_id));
CREATE TABLE IF NOT EXISTS proposal_reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), proposal_id uuid NOT NULL REFERENCES research_proposals(id) ON DELETE RESTRICT, reviewer_user_id uuid REFERENCES users(id) ON DELETE SET NULL, decision proposal_review_decision NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS canonical_facts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL, subject_id uuid NOT NULL, field_key text NOT NULL, current_observation_id uuid NOT NULL REFERENCES observations(id) ON DELETE RESTRICT UNIQUE, accepted_proposal_id uuid REFERENCES research_proposals(id) ON DELETE RESTRICT, superseded_observation_id uuid REFERENCES observations(id) ON DELETE RESTRICT, effective_from timestamptz NOT NULL DEFAULT now(), updated_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(subject_type,subject_id,field_key), CHECK(superseded_observation_id IS NULL OR superseded_observation_id<>current_observation_id));

CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_user_id uuid REFERENCES users(id) ON DELETE SET NULL, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, request_id text, before jsonb, after jsonb, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS entity_merges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text NOT NULL, source_entity_id uuid NOT NULL, target_entity_id uuid NOT NULL, status merge_status NOT NULL DEFAULT 'applied', reason text NOT NULL, source_snapshot jsonb NOT NULL, target_snapshot_before jsonb NOT NULL, target_snapshot_after jsonb NOT NULL, merged_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, reverted_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, merged_at timestamptz NOT NULL DEFAULT now(), reverted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK(source_entity_id<>target_entity_id AND ((status='reverted')=(reverted_at IS NOT NULL))));
CREATE TABLE IF NOT EXISTS saved_views (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, resource_type text NOT NULL, definition jsonb NOT NULL, is_shared boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX IF NOT EXISTS saved_views_owner_resource_name_uidx ON saved_views(owner_user_id,resource_type,lower(name));
CREATE TABLE IF NOT EXISTS imports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requested_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, data_source_id uuid REFERENCES data_sources(id) ON DELETE SET NULL, status import_status NOT NULL DEFAULT 'queued', file_name text NOT NULL, storage_key text NOT NULL, content_sha256 varchar(64) NOT NULL UNIQUE, mapping jsonb NOT NULL DEFAULT '{}', row_count integer, imported_count integer NOT NULL DEFAULT 0, rejected_count integer NOT NULL DEFAULT 0, error jsonb, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((row_count IS NULL OR row_count>=0) AND imported_count>=0 AND rejected_count>=0));
CREATE TABLE IF NOT EXISTS import_rows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_id uuid NOT NULL REFERENCES imports(id) ON DELETE CASCADE, row_number integer NOT NULL CHECK(row_number>0), status import_row_status NOT NULL DEFAULT 'pending', raw_data jsonb NOT NULL, normalized_data jsonb, target_entity_type text, target_entity_id uuid, errors jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(import_id,row_number), CHECK((target_entity_type IS NULL)=(target_entity_id IS NULL)));
CREATE TABLE IF NOT EXISTS scoring_weights (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL DEFAULT 'global', dimension text NOT NULL, weight numeric(8,6) NOT NULL CHECK(weight BETWEEN 0 AND 1), valid_from timestamptz NOT NULL DEFAULT now(), valid_to timestamptz, created_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(scope,dimension,valid_from), CHECK(valid_to IS NULL OR valid_from<valid_to));

CREATE OR REPLACE FUNCTION deny_immutable_record_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% is append-only; % is not allowed',TG_TABLE_NAME,TG_OP USING ERRCODE='55000'; END; $$;
DO $$ DECLARE n text; BEGIN FOREACH n IN ARRAY ARRAY['evidence','observations','ownership_observations','financial_observations','employee_observations','proposal_reviews','audit_events','research_tool_calls','model_usage'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I','deny_'||n||'_mutation',n); EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION deny_immutable_record_change()','deny_'||n||'_mutation',n); END LOOP; END $$;
COMMIT;
